:: FNL is File Name List
SET FNL="%TMP%\swaggers.fnl"
IF EXIST "%FNL%" DEL /F /S "%FNL%"

ECHO https://secure.na1.echosign.com/restapijson/v1/restapi/agreements>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v1/restapi/libraryDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v1/restapi/reminders>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v1/restapi/tokens>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v1/restapi/transientDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v1/restapi/users>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v2/restapi/agreements>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v2/restapi/libraryDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v2/restapi/reminders>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v2/restapi/tokens>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v2/restapi/transientDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v2/restapi/users>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v2/restapi/widgets>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/agreements>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/base_uris>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/groups>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/libraryDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/megaSigns>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/reminders>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/search>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/transientDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/users>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/views>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/widgets>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v3/restapi/workflows>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/agreements>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/base_uris>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/groups>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/libraryDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/megaSigns>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/reminders>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/search>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/transientDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/users>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/views>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/widgets>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v4/restapi/workflows>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/agreements>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/base_uris>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/groups>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/libraryDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/megaSigns>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/reminders>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/search>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/transientDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/users>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/views>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/widgets>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v5/restapi/workflows>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v6/restapi/agreements>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v6/restapi/baseUris>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v6/restapi/groups>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v6/restapi/libraryDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v6/restapi/megaSigns>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v6/restapi/transientDocuments>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v6/restapi/users>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v6/restapi/webhooks>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v6/restapi/widgets>>"%FNL%"
ECHO https://secure.na1.echosign.com/restapijson/v6/restapi/workflows>>"%FNL%"


:: download the tooling
IF NOT EXIST "swagger-codegen-cli.jar" wget "http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar" -O "swagger-codegen-cli.jar"

FOR /F "TOKENS=1,2,3,4,* DELIMS=/" %%a IN ('TYPE "%FNL%"') DO java -jar swagger-codegen-cli.jar generate -i %%a//%%b/%%c/%%d/%%e -l csharp-dotnet2 -o .\%%d